service: serverless-haskell-example

provider:
  name: aws
  runtime: haskell
  region: ap-southeast-2

functions:
  hello:
    handler: serverless-haskell-example.example-exe
  apigw:
    handler: serverless-haskell-example.api-exe
    events:
      - http:
          path: hello/{name}
          method: get

plugins:
  - serverless-haskell
